### ISSUE TITLE
Sec-Websocket-Key not found

### ISSUE THREAD

**Issue by Klaudioz** [thelezend/solana-token-scraper#1]
I was able to get the Discord user account token.
But I couldn't find the `Sec-Websocket-Key` from the headers.

I can see:

Sec-Ch-Ua
Sec-Ch-Ua-Mobile
Sec-Ch-Ua-Platform
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site

**Comment by thelezend** [comment]
Hi @Klaudioz 
To obtain the `Sec-Websocket-Key`, please review the headers of the request under the `WS` category.
<img width="510" alt="image" src="https://github.com/user-attachments/assets/0f6e8e67-63bd-4eb4-83fb-02280fb3ef03">
